"""Post skill results to Slack with HTML report and artifact link.

Runs as the `post` task in the ai-skill job, after the `run` task completes.
Formicary downloads `run` task artifacts into /workspace before calling this script,
so skill_result.json and reports/report.md are available here.

Usage:
    python -m scripts.skill.post

Reads:
    /workspace/skill_result.json        — status, skill name, model
    /workspace/reports/report.md        — full report text (generated by run_skill.py)

Posts:
    1. Slack message with report text + artifact link (HTML upload or formicary URL)
    2. Fallback: plain completion notification with job link

Exit codes: 0=done (always)
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

from scripts.common.config import load_config, get_workspace_dir
from scripts.common.slack_format import format_for_slack
from scripts.standup.slack_client import post_report, notify as slack_notify


def main() -> None:
    config = load_config(required=[])
    workspace = get_workspace_dir(config)

    # Read skill result to get skill name, status, model.
    skill = "skill"
    status = "DONE"
    model = None

    result_path = workspace / "skill_result.json"
    if result_path.exists():
        try:
            data = json.loads(result_path.read_text(encoding="utf-8"))
            skill = data.get("skill") or data.get("name") or skill
            status = data.get("status", status)
            model = data.get("model")
        except Exception as e:
            print(f"[skill-post] WARNING: could not read skill_result.json: {e}", flush=True)

    # Read the report text.
    report_path = workspace / "reports" / "report.md"
    report_text = ""
    if report_path.exists():
        try:
            report_text = report_path.read_text(encoding="utf-8").strip()
        except Exception as e:
            print(f"[skill-post] WARNING: could not read reports/report.md: {e}", flush=True)

    thread_ts = config.get("SLACK_THREAD_TS") or None
    title = f"Skill: {skill}"
    filename = "report.html"  # actual artifact path is reports/report.html

    if report_text:
        slack_text = format_for_slack(report_text)
        if not slack_text:
            slack_text = f"✅ `/{skill}` complete."
        posted = post_report(
            config, slack_text, report_text,
            title=title, filename=filename,
            thread_ts=thread_ts, task_type="run",
        )
        if posted:
            print(f"[skill-post] posted report to Slack (skill={skill} status={status})", flush=True)
        else:
            print(f"[skill-post] WARNING: post_report returned False — falling back to notify", flush=True)
            _notify_fallback(config, skill, status, thread_ts)
    else:
        print(f"[skill-post] no report found — sending completion notification", flush=True)
        _notify_fallback(config, skill, status, thread_ts)

    sys.exit(0)


def _notify_fallback(config: dict, skill: str, status: str, thread_ts: str | None) -> None:
    """Send a plain completion notification when there's no report to post."""
    public_url = (config.get("FORMICARY_PUBLIC_URL") or config.get("FORMICARY_URL") or "").rstrip("/")
    job_id = config.get("JOB_ID") or ""
    icon = ":white_check_mark:" if status not in ("ERROR", "MAX_TURNS_REACHED") else ":x:"
    text = f"{icon} `/{skill}` completed."
    if public_url and job_id:
        text += f"\n<{public_url}/dashboard/jobs/requests/{job_id}|View job in Formicary>"
    try:
        slack_notify(config, text)
    except Exception as e:
        print(f"[skill-post] WARNING: Slack notify failed: {e}", flush=True)


if __name__ == "__main__":
    main()
